#postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
#postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
#postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

#spring_datasource_url: "jdbc:postgresql://database:5432/{{ lookup('env', 'POSTGRES_DB') }}"
#spring_datasource_username: "{{ lookup('env', 'POSTGRES_USER') }}"
#spring_datasource_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"

postgres_db: db
postgres_user: usr
postgres_password: pwd

spring_datasource_url: "jdbc:postgresql://database:5432/db"
spring_datasource_username: usr
spring_datasource_password: pwd